#pragma once

#include <nld/calculus/basis.hpp>
#include <nld/calculus/boundary_condition.hpp>
#include <nld/calculus/bspline_3_basis.hpp>
#include <nld/calculus/concepts.hpp>
#include <nld/calculus/diff.hpp>
#include <nld/calculus/eigenfunctions.hpp>
#include <nld/calculus/eigenvalue_problem.hpp>
#include <nld/calculus/eval.hpp>
#include <nld/calculus/fwd.hpp>
#include <nld/calculus/integral.hpp>
#include <nld/calculus/laplacian.hpp>
#include <nld/calculus/scalar_function.hpp>
#include <nld/calculus/space.hpp>
#include <nld/calculus/spline.hpp>
#include <nld/calculus/tensor_expression.hpp>
#include <nld/calculus/tensor_expression_calculator.hpp>
#include <nld/calculus/tensor_operators.hpp>
#include <nld/calculus/tensor_size.hpp>
#include <nld/calculus/test_functions.hpp>
#include <nld/calculus/weighted_test_functions.hpp>
